- hosts: localhost
  become: yes
  vars: []
  tasks:
    - name: Ensure APT cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 300
    - name: Ensure that the base APT packages are present
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - gcc
        - g++
        - cmake
        - python-dev
        - python-pip
        - python3
        - python3-dev
        - python3-pip
        - libssl-dev
        - redis-tools
        - mysql-client
        - postgresql-client
        - curl
        - wget
        - git
    - name: Enrure that the needed APT keys are present
